#!/bin/bash
export DESKTOP_SESSION=EblanDE
export XDG_CURRENT_DESKTOP=EblanDE

# Main daemons
pcmanfm --desktop &
tint2 & .config/tint2/tint2rc
dunst &
flameshot &
eblan-autostart &
nm-applet &
if [ "$(cat ~/.config/eblan/compositing-enabled)" = "ВКЛ" ]; then
    picom &
fi

# Openbox
exec openbox-session
